# Generated by Django 4.1.7 on 2023-02-19 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('numero', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('tipo', models.CharField(max_length=5)),
                ('region', models.CharField(max_length=255)),
                ('titular', models.CharField(max_length=255)),
                ('tipologia', models.CharField(max_length=255)),
                ('inversion', models.CharField(max_length=255)),
                ('fecha', models.CharField(max_length=255)),
                ('estado', models.CharField(max_length=255)),
                ('mapa', models.CharField(max_length=255)),
            ],
        ),
    ]
