# Generated by Django 4.1.7 on 2023-02-19 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ServiceEnvironmentAPI', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proyecto',
            name='mapa',
        ),
    ]
